image: python:3.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - check
  - lint
  - types
  - test

.base_poetry:
  before_script:
    - pip install poetry
    - poetry install

Poetry check:
  stage: check
  extends: .base_poetry
  script:
    - poetry check

Flake8 code style check:
  stage: lint
  extends: .base_poetry
  script:
    - make flake8
  artifacts:
    paths:
      - build/flake8
    expire_in: 1 day

Static type check:
  stage: types
  extends: .base_poetry
  script:
    - make mypy
  artifacts:
    paths:
      - build/mypy
    expire_in: 1 day

Unit tests:
  stage: test
  extends: .base_poetry
  script:
    - make tox
